### ISSUE TITLE
Title bar is opened in default even though set for False

### ISSUE THREAD

**Issue by Slowik131** [sindrets/atom-title-bar-replacer#63] opened 2020-10-20 09:29 UTC
Just like in the title and on screenshot below - when I open python the title bar is visable though it's set for False. I have to toggle it once again to make it invisible. Windows 10, Atom 1.52.0

![image](https://user-images.githubusercontent.com/58428501/96567544-3318fe80-12c7-11eb-9ecc-5614ed59a565.png)

**Comment by sindrets** [comment] 2021-02-09 12:49
Duplicate of #29. Fixed in v2.0.0.

**Closed by sindrets** 2021-02-09 12:49 UTC
