### ISSUE TITLE
Doesn't remove windows frame and gives error

### ISSUE THREAD

**Issue by 3ckOrTreat** [sindrets/atom-title-bar-replacer#65] opened 2020-12-16 15:50 UTC
![Безымянный](https://user-images.githubusercontent.com/40524858/102371562-59a99c00-3fcf-11eb-8a3c-f22939ecf7c3.png)

**Comment by sindrets** [comment] 2021-02-09 12:47
Duplicate of #36. Fixed in v2.0.0.

**Closed by sindrets** 2021-02-09 12:47 UTC
